=== JamesTheBard/sisyphus-ffmpeg/schema/ffmpeg.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Sisyphus ffmpeg Schema",
  "description": "The Sisyphus ffmpeg schema to import `ffmpeg` options.",
  "type": "object",
  "properties": {
    "input_options": {
      "description": "Main options for `ffmpeg` placed before the input files.",
      "type": "object",
      "properties": {
        "stream_loop": {
          "description": "Set number of times input stream shall be looped",
          "type": "number"
        },
        "recast_media": {
          "description": "Allow forcing a decoder of a different media type than the one detected.",
          "type": "boolean"
        },
        "ss": {
          "description": "The starting position to start reading from (start stream)",
          "type": "string"
        },
        "to": {
          "description": "Stop reading the input at the specified position",
          "type": "string"
        },
        "t": {
          "description": "Stop reading the input after the specified duration",
          "type": "string"
        }
      }
    },
    "sources": {
      "description": "The source files for ffmpeg to use.",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "source_maps": {
      "description": "A map of the sources and the streams they contain.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "source": {
            "description": "The zero-index of the source file to use.",
            "type": "integer"
          },
          "specifier": {
            "description": "The specifier to use to identify streams in the source.",
            "type": "string"
          },
          "stream": {
            "description": "The stream in the source file to use.",
            "type": "integer"
          },
          "optional": {
            "description": "Make the stream optional.",
            "type": "boolean",
            "default": false
          }
        },
        "required": [
          "source"
        ],
        "additionalProperties": false
      },
      "minItems": 1
    },
    "output_maps": {
      "description": "A map of the selected source streams to the output file including options/settings.",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "specifier": {
            "description": "The specifier to use to identify streams in the source.",
            "type": "string"
          },
          "stream": {
            "description": "The stream to process from the source maps.",
            "type": "integer"
          },
          "options": {
            "description": "The options to use for processing the stream.",
            "type": "object"
          },
          "option_set": {
            "description": "The title of a set of options that are held off-server.",
            "type": "string"
          }
        },
        "anyOf": [
          {
            "required": [
              "stream",
              "options"
            ]
          },
          {
            "required": [
              "stream",
              "option_set"
            ]
          }
        ],
        "minItems": 1,
        "additionalProperties": false
      }
    },
    "output_file": {
      "description": "The output file to use.",
      "type": "string"
    },
    "overwrite": {
      "description": "Overwrite the output file if it already exists.",
      "type": "boolean",
      "default": "false"
    }
  },
  "required": [
    "sources",
    "source_maps",
    "output_maps",
    "output_file"
  ],
  "additionalProperties": false
}

=== JamesTheBard/sisyphus-ffmpeg/test.json
{
  "input_options": {
    "ss": "00:10:00",
    "to": "00:11:00"
  },
  "sources": [
    "source_file_1.mkv",
    "source_file_2.ac3"
  ],
  "source_maps": [
    {
      "source": 0,
      "specifier": "v",
      "stream": 0
    },
    {
      "source": 1,
      "specifier": "a",
      "stream": 0
    },
    {
      "source": 0,
      "specifier": "s",
      "stream": 0
    }
  ],
  "output_maps": [
    {
      "specifier": "v",
      "stream": 0,
      "options": {
        "codec": "libx265",
        "crf": 19,
        "pix_fmt": "yuv420p10le",
        "preset": "slow",
        "x265-params": {
          "limit-sao": 1,
          "bframes": 8,
          "psy-rd": 1,
          "psy-rdoq": 2,
          "aq-mode": 3
        }
      }
    },
    {
      "specifier": "a",
      "stream": 0,
      "options": {
        "codec": "libopus",
        "b": "128k",
        "ac": 2,
        "vbr": "on",
        "compression_level": 10,
        "frame_duration": 60,
        "application": "audio"
      }
    },
    {
      "specifier": "s",
      "stream": 0,
      "options": {
        "codec": "copy"
      }
    }
  ],
  "output_file": "/shared/output_file.mkv"
}
